env:
  FOX_SYNC: https://github.com/linastorvaldz/fox-sync.git
  FOX_BRANCH: 14.1
  DT_REPO: https://github.com/naden01/android_device_xiaomi_rodin-twrp.git
  DT_BRANCH: main
  DT_PATH: device/xiaomi/rodin
  DEVICE_MAKEFILE: twrp_rodin-ap2a
  DEVICE_NAME: rodin
  BUILD_TARGET: vendorboot
  TIMEZONE: Asia/Makassar
  RELEASE_REPO: naden01/cirrus/recover-releases
  GH_TOKEN: ENCRYPTED[1e4cda982bac299284382a287906c19be58e4980aa01a8c41628aa79b24c7de3b6190e8d41aef79d815eed29176e5b6a]
  TG_BOT_TOKEN: ENCRYPTED[680cd9aa36ca43615a5a4eb18f5c86667ce1f67f72f1b2d9efde857462af53b22e694ea1d1c8de9255bec52009d9cbca]
  TG_CHAT_ID: ENCRYPTED[da7d452157d0795cfc5fa460f8d7901ff6984f2ca00d63023a09bb1db1a8bbd63b40bc5f5c254bfc502b2832415364a9]

task:
  name: "Build Fox"
  timeout_in: 480m
  container:
    image: eraselk/ubuntu:22.04
    cpu: 8
    memory: 32G

  script:
    - chmod a+x *.sh
    - ./build.sh
    - exit $?
