env:
  FOX_SYNC: https://gitlab.com/OrangeFox/sync.git
  FOX_BRANCH: 14.1
  DT_REPO: https://github.com/naden01/android_device_xiaomi_rodin-twrp.git
  DT_BRANCH: preb
  DT_PATH: device/xiaomi/rodin
  DEVICE_MAKEFILE: twrp_rodin-ap2a
  DEVICE_NAME: rodin
  BUILD_TARGET: vendorboot
  TIMEZONE: Asia/Makassar
  RELEASE_REPO: naden01/cirrus-recovery-releases
  GH_TOKEN: ENCRYPTED[a58ad11dc069acd88d0c69d13cef2a6d0da0397c2af82ffc5b49ae5fcd1f46a71e54bc851390437e15031a77a63d770d]
  TG_BOT_TOKEN: ENCRYPTED[055baf502ee9c2dd407da5d65bddf5b309010c4d44d764ad87a4a3e423a8ffa21dd646f6d864800acf6b2c39ad2c0b72]
  TG_CHAT_ID: ENCRYPTED[faf54823de726535f519cd2b6ff3b4256f5c64b9f5ab6e90a97d618628bae085783f91bb24c311b10de4183a6d8be964]

task:
  name: "Build orangefox"
  timeout_in: 480m
  container:
    image: eraselk/ubuntu:22.04
    cpu: 8
    memory: 32G

  script:
    - chmod a+x *.sh
    - ./build.sh
    - exit $?
